language: node_js
cache: yarn
node_js:
  - '9'
script:
  - yarn run build
  - npm test
deploy:
  provider: npm
  email: rpbiwer+bsexpresstest@gmail.com
  api_key:
    secure: "a10IwskzWjPXvNpGwARxpbxbjxLkjXHLTcNXK8FclP0+v1hQDYeLgdkcoMlmy4Rwe5l2azPBFjiKOi5t8b8Ikft2eSzd540F1uKWhnXGuwjdpt34IO3DyRKKSvZ0CaMnOs6bp+o+CWQLUW1y5LFs5WbeBQ9vi7jLAnzTHzkh6DXU9fhgHg5Q9fwNqxjKkpRgkpuyokbUV3s6N7k+mFltDq9W7EjwIhZN5JL2L208DsC+zZa9FnzKYyD+anHxzLZVzc2E4Bk23f5FVVzNnxp8Ccbk2e4cW/aJblMsSBux6ruuNk4Dwt1pBOmHbymV4GS5bCU6QFJrykUcjLJ46jVXPkrHDEs2lctrW/Fl9MM1t/Kf2e07x4hEong9YaQD0EoDS56W0e1N9QaRThMOMPaQPf33JB2Nf7wyju6Vma/L/sJ+u78CPK23KtV4DUFDK96kNWgGCdFab6LifCI9HeqpdKmBBT5w+xI4AVyXJTYu+2GD2eu6sfVk0A3Rl55Nbi2cX9rtpLoa6+1SQEpf6Zeu0aT5FfU2L5up0ohjLd6KpzdfNpYHF3mxvJzKBAO+O8zVQX0oH6dADCtDwONMsl1BBJ+GiB8bCg1wmJX9tiWeQvRSrevciup/T9sIQ0QPk6jjVx5nh+sMeDb2HVI0nN5H7S4siu7s/24xiS2IR2wevY4="
  on:
    branch: cd
    repo: ryb73/bs-express
